# The numpy.random package

![NumPy.png](img/NumPy.png)

## What is a NumPy?

NumPy is a Python package which stands for ‘Numerical Python’. It is an extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of NumPy guarantee great execution speed.

Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays. The implementation is even aiming at huge matrices and arrays, better known under the heading of "big data". Besides that, the module supplies a large library of high-level mathematical functions to operate on these matrices and arrays.

### Advantages of using NumPy with Python:

- array oriented computing
- efficiently implemented multi-dimensional arrays
- designed for scientific computation


### How to install Numpy on Python?

In most use cases the best way to install NumPy on your system is by using a pre-built package for your operating system. Please see http://scipy.org/install.html or https://solarianprogrammer.com/2017/02/25/install-numpy-scipy-matplotlib-python-3-windows/ for links to available options.

## Random sampling (numpy.random)

Phyton comes with a random module which give us a wide variety of functions for generating random numbers. This is useful if we want to add unpredictability for a game or to run Monte Carlo simulations read here: http://www.palisade.com/risk/monte_carlo_simulation.asp.
This module implements pseudo-random number generators for various distributions.For integers, uniform selection from a range. For sequences, uniform selection of a random element, a function to generate a random permutation of a list in-place, and a function for random sampling without replacement.

##### To import NumPy you need to write the following code:

In [1]:
# Import numpy for random package
import numpy as np

## 1. Simple random data

### 1.1 Example: numpy.random rand
__Random values in a given shape.__

__numpy.random.rand(d0, d1, …, dn)__ : Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [2]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 1D array with five random values.
np.random.rand(5)

array([0.95589422, 0.4024452 , 0.91883627, 0.61533937, 0.28015369])

In [3]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 2D array with thirty random values
np.random.rand(6,5)

array([[0.33307687, 0.35458929, 0.30283474, 0.48333126, 0.37556965],
       [0.21045804, 0.02198673, 0.76799165, 0.39691645, 0.87206422],
       [0.81123824, 0.86288246, 0.9191096 , 0.86238774, 0.54761799],
       [0.38112728, 0.34643761, 0.19406238, 0.03697345, 0.50395494],
       [0.73555212, 0.23828284, 0.94307302, 0.30434326, 0.34554835],
       [0.20863531, 0.06506956, 0.87840304, 0.68196207, 0.99683417]])

### 1.2 Example: numpy.random randn
__Return a sample (or samples) from the “standard normal” distribution.__

__numpy.random.randn(d0, d1, …, dn)__ : creates an array of specified shape and fills it with random values as per standard normal distribution.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [4]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 1D Array with four random values
np.random.randn(4)

# Returns 1D Array filled with random floating-point samples from the standard normal distribution.

array([-0.78535622,  0.98384727, -0.84555541, -2.02921035])

In [5]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 3D Array with random values
np.random.randn(2,4,3)
# Returns 3D Array filled with random floating-point samples from the standard normal distribution.

array([[[ 1.45265669,  0.24045797, -0.16224304],
        [-0.93947973,  0.09347218,  0.40420444],
        [ 0.4146563 ,  0.97252121,  0.84304058],
        [-0.34244149,  0.18758335,  0.88440763]],

       [[ 0.46480182, -1.07002697, -1.72410165],
        [-0.19390897, -1.04382046,  0.33267445],
        [-0.15755565, -0.98292747,  0.65199907],
        [-0.32812456,  1.04883294, -0.914723  ]]])

### 1.3 Example: numpy.random randint
__Return random integers from low (inclusive) to high (exclusive).__

__numpy.random.randint(low, high=None, size=None, dtype='l')__ : creates size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.



In [6]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 1D Array with 8 integers between 9-19
np.random.randint(9,20,size=8)

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([12, 15, 19, 19, 14, 19, 17, 10])

In [7]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 3D Array with 6x4 integers between 0-4
np.random.randint(0,5,size=(3, 4, 6))

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([[[0, 4, 2, 4, 0, 0],
        [2, 1, 2, 3, 3, 2],
        [0, 1, 0, 2, 3, 2],
        [3, 2, 2, 1, 0, 1]],

       [[4, 2, 1, 2, 1, 4],
        [3, 2, 0, 0, 4, 1],
        [1, 3, 4, 3, 1, 4],
        [0, 1, 3, 0, 4, 1]],

       [[1, 0, 0, 2, 2, 3],
        [0, 4, 3, 4, 4, 4],
        [1, 2, 2, 1, 0, 0],
        [2, 4, 0, 1, 2, 0]]])

## 2. Permutations

## 3. Distributions

## 4. Random generator

### References:
https://www.geeksforgeeks.org/python-numpy/