# The numpy.random package

![NumPy.png](img/NumPy.png)

## What is a NumPy?

NumPy is a Python package which stands for ‘Numerical Python’. It is an extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of NumPy guarantee great execution speed.

Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays. The implementation is even aiming at huge matrices and arrays, better known under the heading of "big data". Besides that, the module supplies a large library of high-level mathematical functions to operate on these matrices and arrays.

### Advantages of using NumPy with Python:

- array oriented computing
- efficiently implemented multi-dimensional arrays
- designed for scientific computation


### How to install Numpy on Python?

In most use cases the best way to install NumPy on your system is by using a pre-built package for your operating system. Please see http://scipy.org/install.html or https://solarianprogrammer.com/2017/02/25/install-numpy-scipy-matplotlib-python-3-windows/ for links to available options.

## Random sampling (numpy.random)

Phyton comes with a random module which give us a wide variety of functions for generating random numbers. This is useful if we want to add unpredictability for a game or to run Monte Carlo simulations read here: http://www.palisade.com/risk/monte_carlo_simulation.asp.
This module implements pseudo-random number generators for various distributions.For integers, uniform selection from a range. For sequences, uniform selection of a random element, a function to generate a random permutation of a list in-place, and a function for random sampling without replacement.

##### To import NumPy you need to write the following code:

In [1]:
# Import numpy for random package
import numpy as np

## 1. Simple random data

### 1.1 Example: numpy.random rand
__Random values in a given shape.__

__numpy.random.rand(d0, d1, …, dn)__ : Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [2]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 1D array with five random values.
np.random.rand(5)

array([0.55077289, 0.4234414 , 0.94817016, 0.0783634 , 0.96970645])

In [3]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 2D array with thirty random values
np.random.rand(6,5)

array([[0.45792538, 0.10992089, 0.33295501, 0.27173459, 0.95848888],
       [0.16139051, 0.83828963, 0.72021779, 0.44874801, 0.49532649],
       [0.45587596, 0.17187794, 0.96645794, 0.45110709, 0.93898931],
       [0.84914936, 0.52700308, 0.66141114, 0.68008189, 0.24399395],
       [0.45847165, 0.25201545, 0.60772582, 0.79295786, 0.80552202],
       [0.25880561, 0.77032716, 0.42721216, 0.04081723, 0.67864186]])

### 1.2 Example: numpy.random randn
__Return a sample (or samples) from the “standard normal” distribution.__

__numpy.random.randn(d0, d1, …, dn)__ : creates an array of specified shape and fills it with random values as per standard normal distribution.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [4]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 1D Array with four random values
np.random.randn(4)

# Returns 1D Array filled with random floating-point samples from the standard normal distribution.

array([-0.33232275, -0.2030049 , -0.24095222,  0.91481643])

In [5]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 3D Array with random values
np.random.randn(2,4,3)
# Returns 3D Array filled with random floating-point samples from the standard normal distribution.

array([[[ 0.03800739,  0.95309357, -1.23968771],
        [-0.32072208, -0.39941671, -0.97940528],
        [-0.70111893,  0.05406288,  0.40712502],
        [ 0.06173587, -0.07089838, -0.88677431]],

       [[ 2.34270033, -0.05948884,  1.33825551],
        [ 0.41847243, -1.12258412, -0.51380842],
        [ 0.83302352, -0.38923185,  1.43945077],
        [-0.69814941, -1.03166299,  0.23908329]]])

### 1.3 Example: numpy.random randint
__Return random integers from low (inclusive) to high (exclusive).__

__numpy.random.randint(low, high=None, size=None, dtype='l')__ : creates size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.



In [6]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 1D Array with 8 integers between 9-19
np.random.randint(9,20,size=8)

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([ 9, 14, 18, 14, 14, 18, 11, 13])

In [7]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 3D Array with 6x4 integers between 0-4
np.random.randint(0,5,size=(3, 4, 6))

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([[[1, 2, 4, 3, 3, 4],
        [4, 1, 4, 4, 4, 2],
        [0, 4, 0, 2, 2, 3],
        [1, 1, 2, 2, 0, 0]],

       [[2, 3, 4, 4, 1, 2],
        [1, 3, 1, 4, 3, 1],
        [3, 1, 3, 4, 1, 1],
        [0, 3, 3, 0, 4, 4]],

       [[3, 2, 0, 3, 1, 4],
        [3, 1, 3, 4, 0, 1],
        [2, 4, 3, 1, 4, 1],
        [1, 4, 3, 4, 4, 1]]])

### 1.4 Example numpy.random.choice
__Generates a random sample from a given 1-D array__

__numpy.random.choice(a, size=None, replace=True, p=None)__

In [8]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates list of integers
np.random.choice([3, 4, 6])

# Returns one integer from the list

3

In [9]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates list of strings
np.random.choice(["Dog", "Cat", "Duck"])

# Returns one string from the list

'Cat'

In [10]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates array of animals
animal_arr = ['cat', 'rabbit', 'dog', 'horse']

# Creates array which takes list of animals as the first argument. 
# Second argument defing number of strings. 
# Third argument specifies the probability of each sting

np.random.choice(animal_arr,10, p=[0.2, 0, 0.6, 0.2])

array(['dog', 'dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'dog', 'dog',
       'cat'], dtype='<U6')

## 2. Permutations

A permutation, alternatively known as an ‘arrangement number’ or ‘ordering’ is an arrangement of the elements of an ordered list into a one-to-one mapping with itself. The permutation of a given arrangement is given by indicating the positions of the elements after re-arrangement. For example, if one started with elements [x, y, a, b] (in that order) and they were reordered as [x, y, b, a] then the permutation would be [0, 1, 3, 2]. 

### 2.1 Example numpy.random.shuffle
__numpy.random.shuffle(x)__ : Modify a sequence in-place by shuffling its contents.

Shuffle the sequence x in place. The optional argument random is a 0-argument function returning a random float in [0.0, 1.0); by default, this is the function random().

Note that for even rather small len(x), the total number of permutations of x is larger than the period of most random number generators; this implies that most permutations of a long sequence can never be generated.

In [11]:
# numpy.random.shuffle() method 

# Import numpy 
import numpy as np

# Creates 1D array with inegers between 0-4
arr = np.arange(5)
# This function shuffles the array
np.random.shuffle(arr)
# Prints shuffled array
arr

array([2, 0, 4, 3, 1])

In [12]:
# numpy.random.shuffle() method 

# Import numpy 
import numpy as np

# Creates 2D array with integers between 0-19 , only shuffled along the first axis
arr = np.arange(20).reshape((5, 4))
# This function shuffles the array
np.random.shuffle(arr)
# Prints shuffled array
arr

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [12, 13, 14, 15]])

__numpy.random.shuffle(x[, random])__ : shuffle method takes two parameters. out of the two random is an optional parameter.

Shuffle method used to shuffle the sequence in place. i.e it changes the position of items in a list. we call it as a randomizes the items of a list in place.For example, Shuffling a pack of cards, shuffling list of a string

In [13]:
# numpy.random.shuffle() method

# Import numpy 
import numpy as np

# Creates list on integers
number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
# Prints list 
print ("Original list : ",  number_list)
#shuffle method 
np.random.shuffle(number_list) 
# Prints shuffled list
print ("List after first shuffle  : ",  number_list)
np.random.shuffle(number_list)
# Prints shuffled list
print ("List after second shuffle : ",  number_list)

Original list :  [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
List after first shuffle  :  [14, 7, 28, 21, 63, 49, 70, 42, 56, 35]
List after second shuffle :  [70, 42, 63, 49, 14, 21, 35, 56, 7, 28]


## 3. Distributions

## 4. Random generator

### References:
https://www.geeksforgeeks.org/python-numpy/

https://pynative.com/python-random-module/