# The numpy.random package

![NumPy.png](img/NumPy.png)

## What is a NumPy?

NumPy is a Python package which stands for ‘Numerical Python’. It is an extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of NumPy guarantee great execution speed.

Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays. The implementation is even aiming at huge matrices and arrays, better known under the heading of "big data". Besides that, the module supplies a large library of high-level mathematical functions to operate on these matrices and arrays.

### Advantages of using NumPy with Python:

- array oriented computing
- efficiently implemented multi-dimensional arrays
- designed for scientific computation


### How to install Numpy on Python?

In most use cases the best way to install NumPy on your system is by using a pre-built package for your operating system. Please see http://scipy.org/install.html or https://solarianprogrammer.com/2017/02/25/install-numpy-scipy-matplotlib-python-3-windows/ for links to available options.

## Random sampling (numpy.random)

Phyton comes with a random module which give us a wide variety of functions for generating random numbers. This is useful if we want to add unpredictability for a game or to run Monte Carlo simulations read here: http://www.palisade.com/risk/monte_carlo_simulation.asp.
This module implements pseudo-random number generators for various distributions.For integers, uniform selection from a range. For sequences, uniform selection of a random element, a function to generate a random permutation of a list in-place, and a function for random sampling without replacement.

##### To import NumPy you need to write the following code:

In [1]:
# Import numpy for random package
import numpy as np

## 1. Simple random data

### 1.1 Example: numpy.random rand
__Random values in a given shape.__

__numpy.random.rand(d0, d1, …, dn)__ : Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [2]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 1D array with five random values.
np.random.rand(5)

array([0.77717963, 0.07592045, 0.64765732, 0.41269104, 0.7650873 ])

In [3]:
# numpy.random.rand() method 

# Import numpy 
import numpy as np

# Creates 2D array with thirty random values
np.random.rand(6,5)

array([[0.09685481, 0.3200197 , 0.69371668, 0.29976886, 0.51391725],
       [0.40762584, 0.54431195, 0.38191904, 0.80300163, 0.83259612],
       [0.47610518, 0.1156465 , 0.9709434 , 0.35374113, 0.41344469],
       [0.7824766 , 0.62204095, 0.36063662, 0.62031668, 0.00497332],
       [0.49192335, 0.59113241, 0.8382045 , 0.68153632, 0.00851258],
       [0.12805484, 0.23987902, 0.89190029, 0.51644426, 0.18815689]])

### 1.2 Example: numpy.random randn
__Return a sample (or samples) from the “standard normal” distribution.__

__numpy.random.randn(d0, d1, …, dn)__ : creates an array of specified shape and fills it with random values as per standard normal distribution.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [4]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 1D Array with four random values
np.random.randn(4)

# Returns 1D Array filled with random floating-point samples from the standard normal distribution.

array([-1.13439288, -0.31620817,  0.32534877,  0.94484868])

In [5]:
# numpy.random.randn() method 

# Import numpy 
import numpy as np

# Creates 3D Array with random values
np.random.randn(2,4,3)
# Returns 3D Array filled with random floating-point samples from the standard normal distribution.

array([[[ 0.94934063, -1.10444516, -0.60218304],
        [-0.46168668, -0.67419562, -0.62778819],
        [ 2.24316324,  0.10381158,  0.0908062 ],
        [ 1.195238  , -0.25563228, -0.04511747]],

       [[-0.37270231,  0.62261043, -0.00755647],
        [ 0.75787016, -0.6634521 ,  1.11189577],
        [ 0.22987464, -0.85801775, -0.99761056],
        [-0.96349239, -0.04172061,  0.4741583 ]]])

### 1.3 Example: numpy.random randint
__Return random integers from low (inclusive) to high (exclusive).__

__numpy.random.randint(low, high=None, size=None, dtype='l')__ : creates size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.



In [6]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 1D Array with 8 integers between 9-19
np.random.randint(9,20,size=8)

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([18,  9, 19, 14, 18, 13, 19, 13])

In [7]:
# numpy.random.randint() method 

# Import numpy 
import numpy as np

# Creates 3D Array with 6x4 integers between 0-4
np.random.randint(0,5,size=(3, 4, 6))

# Returns size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

array([[[4, 4, 0, 0, 3, 1],
        [1, 1, 3, 2, 1, 4],
        [4, 0, 3, 1, 4, 1],
        [0, 0, 2, 3, 1, 4]],

       [[2, 1, 0, 4, 3, 4],
        [1, 1, 3, 0, 2, 2],
        [2, 2, 0, 1, 2, 2],
        [1, 3, 4, 4, 0, 3]],

       [[2, 3, 0, 0, 1, 3],
        [2, 1, 0, 0, 2, 4],
        [3, 4, 2, 2, 0, 2],
        [1, 1, 3, 3, 3, 4]]])

### 1.4 Example numpy.random.choice
__Generates a random sample from a given 1-D array__

__numpy.random.choice(a, size=None, replace=True, p=None)__

In [8]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates list of integers
np.random.choice([3, 4, 6])

# Returns one integer from the list

4

In [9]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates list of strings
np.random.choice(["Dog", "Cat", "Duck"])

# Returns one string from the list

'Duck'

In [10]:
# numpy.random.choice() method 

# Import numpy 
import numpy as np

# Creates array of animals
animal_arr = ['cat', 'rabbit', 'dog', 'horse']

# Creates array which takes list of animals as the first argument. 
# Second argument defing number of strings. 
# Third argument specifies the probability of each sting

np.random.choice(animal_arr,10, p=[0.2, 0, 0.6, 0.2])

array(['dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat', 'cat',
       'dog'], dtype='<U6')

## 2. Permutations

A permutation, alternatively known as an ‘arrangement number’ or ‘ordering’ is an arrangement of the elements of an ordered list into a one-to-one mapping with itself. The permutation of a given arrangement is given by indicating the positions of the elements after re-arrangement. For example, if one started with elements [x, y, a, b] (in that order) and they were reordered as [x, y, b, a] then the permutation would be [0, 1, 3, 2]. 

### 2.1 Example numpy.random.shuffle
__numpy.random.shuffle(x)__ : Modify a sequence in-place by shuffling its contents.

Shuffle the sequence x in place. The optional argument random is a 0-argument function returning a random float in [0.0, 1.0); by default, this is the function random().

Note that for even rather small len(x), the total number of permutations of x is larger than the period of most random number generators; this implies that most permutations of a long sequence can never be generated.

In [11]:
# numpy.random.shuffle() method 

# Import numpy 
import numpy as np

# Creates 1D array with inegers between 0-4
arr = np.arange(5)
# This function shuffles the array
np.random.shuffle(arr)
# Prints shuffled array
arr

array([1, 0, 4, 2, 3])

In [12]:
# numpy.random.shuffle() method 

# Import numpy 
import numpy as np

# Creates 2D array with integers between 0-19 , only shuffled along the first axis
arr = np.arange(20).reshape((5, 4))
# This function shuffles the array
np.random.shuffle(arr)
# Prints shuffled array
arr

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7]])

__numpy.random.shuffle(x[, random])__ : shuffle method takes two parameters. out of the two random is an optional parameter.

Shuffle method used to shuffle the sequence in place. i.e it changes the position of items in a list. we call it as a randomizes the items of a list in place.For example, Shuffling a pack of cards, shuffling list of a string

In [13]:
# numpy.random.shuffle() method

# Import numpy 
import numpy as np

# Creates list on integers
number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
# Prints list 
print ("Original list : ",  number_list)
#shuffle method 
np.random.shuffle(number_list) 
# Prints shuffled list
print ("List after first shuffle  : ",  number_list)
np.random.shuffle(number_list)
# Prints shuffled list
print ("List after second shuffle : ",  number_list)

Original list :  [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
List after first shuffle  :  [21, 14, 63, 56, 7, 35, 42, 49, 70, 28]
List after second shuffle :  [35, 63, 7, 14, 21, 70, 28, 56, 42, 49]


### 2.2 Exmaple numpy.random.permutation
__numpy.random.permutation(x)__: Randomly permute a sequence, or return a permuted range.
If x is a multi-dimensional array, it is only shuffled along its first index.

In [14]:
# numpy.random.permutation() method

# Import numpy 
import numpy as np

# If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.
# numpy.random.permutation(x)
# Creates range of integeres between 0-4
np.random.permutation(5)
# Returns permuted sequence 

array([4, 2, 1, 0, 3])

In [15]:
# numpy.random.permutation() method

# Import numpy 
import numpy as np

# If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.
# numpy.random.permutation(x)
# Creates array with given integers
np.random.permutation([5, 7, 20, 21, 30])
# Returns permuted sequence

array([ 5, 20, 30,  7, 21])

In [16]:
# numpy.random.permutation() method

# Import numpy 
import numpy as np

# If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.
# numpy.random.permutation(x)
# Creates 3D array with integers that are between 0-23
arr = np.arange(24).reshape((3, 4, 2))
# Returns array range
np.random.permutation(arr)

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

#### Shuffle vs Permutation

In [17]:
# numpy.random.shuffle() method vs # numpy.random.permutation() method

# Import numpy 
import numpy as np

x = np.arange(5)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(5))

[1 3 4 2 0]
Same result using permutation():
[3 0 4 2 1]


## 3. Distributions
The distribution of a statistical data set (or a population) is a listing or function showing all the possible values (or intervals) of the data and how often they occur. When a distribution of categorical data is organized, you see the number or percentage of individuals in each group. When a distribution of numerical data is organized, they’re often ordered from smallest to largest, broken into reasonably sized groups (if appropriate), and then put into graphs and charts to examine the shape, center, and amount of variability in the data.The world of statistics includes dozens of different distributions for categorical and numerical data; the most common ones have their own names. 

### 3.1 Examle numpy.random.normal
__numpy.random.normal(loc=0.0, scale=1.0, size=None)__
A normal distribution in statistics is distribution that is shaped like a bell curve.
With a normal distribution plot, the plot will be centered on the mean value.
In a normal distribution, 68% of the data set will lie within ±1 standard deviation of the mean. 95% of the data set will lie within ±2 standard deviations of the mean. And 99.7% of the data set will lie within ±3 standard deviations of the mean.

In [18]:
# numpy.random.normal() method

# Import numpy
import numpy as np 
# Import matplotlib
import matplotlib.pyplot as plt

# Creates the data for a normal distribution plot centered around a mean of 50, showing 2 standard deviations of the data, and creates 10,000 random data points that are of normal distribution.
gaussian_numbers = np.random.normal(50,2, 10000)
# Generates histogram
plt.hist(gaussian_numbers)
# Adds title
plt.title("Gaussian Histogram")
# Creates lable 
plt.xlabel("Value")
# Creates lable 
plt.ylabel("Frequency")
# Shows plot
plt.show()

<Figure size 640x480 with 1 Axes>

## 4. Random generator

### References:
https://www.geeksforgeeks.org/python-numpy/

https://pynative.com/python-random-module/

https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html#simple-random-data

https://docs.python.org/2/library/random.html

https://towardsdatascience.com/a-quick-introduction-to-the-numpy-library-6f61b7dee4db

https://www.dataquest.io/blog/numpy-tutorial-python/

https://www.edureka.co/blog/python-numpy-tutorial/?utm_source=quora&utm_medium=crossposting&utm_campaign=social-media-sep-aj

https://machinelearningmastery.com/statistical-data-distributions/

https://www.vaishalilambe.com/blog/statistics-distribution